package pl.uj.edu.readability;

import java.util.Arrays;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class TextStatParserTest {

    private final String text = "Tomasz Judym wracał przez Champs Elysees z Lasku Bulońskiego, dokąd jeździł ze swej dzielnicy koleją obwodową. Lato, RoślinySzedł wolno, noga za nogą, wyczuwając coraz większy wskutek upału ciężar własnej marynarki i kapelusza. Istny potop blasku słonecznego zalewał przestwór. Nad odległym widokiem gmachów rzucających się w oczy od Łuku Tryumfalnego wisiał różowy pyłek, który już począł wżerać się niby rdza nawet w śliczne, jasnozielone liście wiosenne, nawet w kwiatuszki paulowni[2]. Z wszystkich, zdawało się, stron płynął zapach akacji. Na żwirze, dokoła pniów, pod budynkami, w rynsztokach leżały jej białe kwiatki z ośrodkiem czerwonawym, jakby skrwawionym od ukłucia śmierci. Pył bezlitosny zasypywał je niepostrzeżenie.\n" +
            "Zbliżała się godzina spaceru wielkiego świata i pola drgać zaczynały od ruchu karet. Na drewnianym bruku dudnił jednostajny łoskot jakby oddalona mowa wielkiej fabryki. Przebiegały piękne, lśniące rumaki, migotała ich uprząż, pudła, sprychy lekkich pojazdów — i mknęły, mknęły, mknęły bez ustanku wiosenne stroje kobiece o barwach czystych, rozmaitych i sprawiających rozkoszne wrażenie, jakby natury dziewiczej. Kiedy niekiedy wynurzała się z powodzi osób jadących twarz subtelna, wydelikacona, tak nie do uwierzenia piękna, że widok jej był pieszczotą dla wzroku i nerwów. Wyrywał z piersi tęskne westchnienie jak za szczęściem — i ginął unosząc je w mgnieniu oka ze sobą.\n" +
            "Judym znalazł pod osłoną kasztanów brzeg wolnej ławy i z wielką satysfakcją usiadł tam w sąsiedztwie starej i wąsatej niańki dwojga dzieci. Zdjął kapelusz i wlepiwszy wzrok w rzekę pojazdów, walącą środkiem ulicy, z wolna wystygał. Na chodnikach przybywało coraz więcej osób ubranych wykwintnie — lśniących cylindrów, jasnych paltotów i staników. W pewnej chwili stare babsko z chytrymi oczami wprowadziło między strojny tłum młode koźlątko z sierścią jak śnieg bielutką. Stado dzieci postępowało za koziołkiem uwielbiając go gestami, oczyma i tysiącem okrzyków. Kiedy indziej wielki obdartus czerwony na gębie przeleciał jak fiksat, wywrzaskując głosem ochrypłym rezultat ostatniego biegu koni. I znowu spokojnie, równo, uroczo płynęła rzeka ludzka na chodnikach, a środkiem rwał jej nurt bystry, uwieńczony pianą tkanin przecudnych, lekkich, w oddali niebieskawozielonych…\n" +
            "RoślinyKażdy rozpuszczony liść rzucał na biały żwir z okrągłych kamyków wyraźne odbicie swego kształtu. Cienie te posuwały się z wolna, jak mała wskazówka po białej tarczy zegara. Na ławkach było już pełno, a tymczasem cień opuścił miejsce zajęte przez Judyma i ustąpił je roztapiającej kaskadzie słońca. Naokół innego asilum[3] nie było, więc doktor rad nierad wstał i powlókł się dalej ku placowi Zgody. Z niecierpliwością wyczekiwał, kiedy można będzie przemknąć się wskroś istnego odmętu karet, powozów, dorożek, bicyklów[4] i pieszych na zakręcie głównej fali pędzącej od bulwarów w stronę Pól Elizejskich. Wreszcie stanął pod obeliskiem[5] i poszedł w głąb ogrodu des Tuileries. Tam było prawie pusto. Tylko nad nudnymi sadzawkami bawiły się blade dzieci i w głównym szpalerze kilku mężczyzn rozebranych do koszuli grało w tenisa. Minąwszy ogród Judym zwrócił się ku rzece z zamiarem wędrowania w cieniu murów na placyk przed kościołem Saint-Germain-l'Auxerrois i ogarnięcia bez troski miejsca na imperiale[6]. W owej chwili stało w jego myśli puste kawalerskie mieszkanie aż na Boulevard Voltaire, gdzie od roku nocował, i mierziło go pustką swych ścian, banalnością sprzętów i nieprzezwyciężoną, cudzoziemską nudą wiejącą z każdego kąta. Pracować mu się nie chciało, iść do kliniki — za, nic na świecie.\n" +
            "Znalazł się na Quai du Louvre i z uczuciem błogości w karku i plecach zatrzymał pod cieniem pierwszego kasztana bulwaru. Ospałym wzrokiem mierzył brudną, prawie czarną wodę Sekwany. Gdy tak sterczał na podobieństwo latarni, zapaliła się w nim myśl, jakby z zewnątrz wniesiona do wnętrza głowy: „Dlaczegóż, u licha, nie miałbym pójść do tego Luwru?…”\n" +
            "Skręcił na miejscu i wszedł na wielki dziedziniec. W cieniach przytulonych do grubego muru, w które zanurzył się niby w głębie wody, dotarł do głównego wejścia i znalazł się w chłodnych salach pierwszego piętra. Dokoła stały odwieczne posągi bogów, jedne wielkości niezwykłej, inne naturalnej, a wszystkie prawie z nosami i rękoma uszkodzonymi w sposób bezbożny. Judym nie zwracał uwagi na tych zdegradowanych władców świata. Czasami zatrzymywał się przed którym, ale przeważnie wówczas, gdy go uderzył jakiś zabawny despekt boskich kształtów. Nade wszystko interesowała go sprawa odpoczynku w doskonałym chłodzie i z dala od wrzawy ulicy paryskiej. Szukał też nie tyle arcydzieł, ile ławki, na której by mógł usiąść. Zdybał ją po długiej wędrówce z sali do sali w narożnym zetknięciu się dwu długich galerii, przeznaczonym na schronienie dla Wenus z wyspy Melos.\n" +
            "Miłość, Kobieta, Sztuka W zakątku tworzącym jakby niewielką izbę, oświetloną jednym oknem, stoi na niewysokim piedestale tors białej Afrodyty. Sznur owinięty czerwonym pluszem nikomu do niej przystępu nie daje. Judym widział już był ten cenny posąg, ale nie zwracał nań uwagi, jak na wszelkie w ogóle dzieła sztuki. Teraz zdobywszy w cieniu pod ścianą wygodną ławeczkę jął dla zabicia czasu patrzeć w oblicze marmurowej piękności. Głowa jej zwrócona była w jego stronę i martwe oczy zdawały się patrzeć. Schylone czoło wynurzało się z mroku i, jakby dla obaczenia czegoś, brwi się zsunęły. Judym przyglądał się jej nawzajem i wtedy dopiero ujrzał małą, niewidoczną fałdę między brwiami, która sprawia, że ta głowa, że ta bryła kamienna w istocie — myśli. Z przenikliwą siłą spogląda w mrok dokoła leżący i rozdziera go jasnymi oczyma. Zatopiła je w skrytości życia i do czegoś w nim uśmiech swój obraca. Wytężywszy rozum nieograniczony i czysty, posiadła wiadomość o wszystkim, zobaczyła wieczne dnie i prace na ziemi, noce i łzy, które w ich mroku płyną. Jeszcze z białego czoła bogini nie zdążyła odejść mądra o tym zaduma, a już wielka radość dziewicza pachnie z jej ust rozmarzonych. W uśmiechu ich zamyka się wyraz uwielbienia. Dla miłości szczęśliwej. Dla uczestnictwa wolnego ducha i wolnego ciała w życiu bezgrzesznej przyrody. Dla ostrej potęgi zachwytu zmysłów, którego nie stępiły jeszcze ani praca, ani zgryzota, siostry rodzone, siostry nieszczęsne. Uśmiech bogini pozdrawia nadchodzącego z daleka. Oto zakochała się w pięknym śmiertelniku Adonisie[7]… Cudne marzenia pierwszej miłości rozkwitły w łonie jej jako kwiat siedmioramienny amarylisa. Barki jej wąskie, wysmukłe, okrągłe dźwignęły się do góry. Dziewicze łono drży od westchnienia… Długi szereg wieków, który odtrącił jej ręce, który zrabował jej ciało od piersi i zorał prześliczne ramiona szczerbami, nie zdołał go zniweczyć. Stała tak w półmroku „wynurzająca się”, Anadiomene[8], niebiańska, która roznieca miłość. Obnażone jej włosy związane były w piękny węzeł, krobylos. Podłużna, smagła twarz tchnęła nieopisanym urokiem.";

    @Test
    public void parseWords() {
        TextStatParser textStatParser = new TextStatParser();

        TextStat textStat = textStatParser.generateStat(text);
        assertThat(textStat)
                .isEqualTo(new TextStat(text, Arrays.asList(text.split(".")), 174, 1019, 2324, 5691));
    }
}